name: Build Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4.0.0
      with:
        python-version: '3.x'

    - name: Create venv
      id: octoprint-venv
      uses: syphar/restore-virtualenv@v1.2
      with:
        custom_virtualenv_dir: OctoPrint\venv

    - name: Build Installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "OctoPrint Setup.iss"
      shell: cmd

    - name: Upload the installer as an artifact
      uses: actions/upload-artifact@v2
      if: ${{ github.event_name != 'pull_request' }}
      with:
        path: "Output/OctoPrint Setup.exe"
        name: octoprint-setup

