name: Build Installer

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v4.0.0
      with:
        python-version: '3.x'

    - name: 🔎 Get OctoPrint Version
      id: octoprint_version
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: OctoPrint/OctoPrint
        excludes: prerelease, draft

    - name: Build Installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "OctoPrint Setup.iss"
      shell: cmd

    - name: Rename Installer
      run: |
        "copy '${{ github.workspace }}\Output\OctoPrint Setup.exe' '${{ github.workspace }}\Output\OctoPrint Setup ${{ steps.octoprint_version.outputs.release }}.exe'"

    - uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: ${{ steps.octoprint_version.outputs.release }} # tag name to delete
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "🔖 Create release & attach assets"
      uses: softprops/action-gh-release@v1
      with:
        name: "OctoPrint ${{ steps.octoprint_version.outputs.release }} Setup for Windows"
        tag_name: "${{ steps.octoprint_version.outputs.release }}"
        body: "OctoPrint Setup created with Inno Setup using WinPython, winsw, and GitHub Actions."
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          Output\OctoPrint Setup.exe
